--Creating the company admin user
CREATE USER 'Admin@telecomlb'@'127.0.0.1' IDENTIFIED BY 'ITADMIN@Tel$1120#7';
--Revoke all default Privileges
REVOKE ALL PRIVILEGES ON *.* FROM 'Admin@telecomlb'@'127.0.0.1' ;  
-- Granting the necessary privileges 
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EXECUTE ON *.* TO 'Admin@telecomlb'@'127.0.0.1' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDA
TES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
--Reload SQL Users and Privileges
FLUSH PRIVILEGES;