device = "    switch L4,    Aruba,           10,     FHO89 "
print(f"string={device}")
print("-------------------------------------------------------------------")
print(f"print using split:\n     {device.split(',')}")
print("-------------------------------------------------------------------")
print(f"print using strip & split:\n     {device.strip().split(',')}")
print("-------------------------------------------------------------------")
print(f"remove blanks:\n     {device.replace(' ','').split(',')}")
print("-------------------------------------------------------------------")
print(f"replace comma with colomn:\n     {device.replace(' ','').replace(',',':')}",
      "\n         this is just a string!")
print("-------------------------------------------------------------------")
print(f"loop with strip and split:     ")
print("\t", end='')
for item in device.split(','):
    print(f"{item.strip()}", end=',')
print("\n")
print("-------------------------------------------------------------------")
print("using comprehension:     ")
device_detail = [item.strip() for item in device.split(',')]
print(f"\t {device_detail}")
print("-------------------------------------------------------------------")
print("manipulate strings:")
model = input("\tdevice model:")
print(f"\tmodel uppercase:{model.upper()}")
print("-------------------------------------------------------------------")
print("Fiding in string:")
index = device.find(model)
print(f"\t{model} found at location {index}")
